// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {plans} from '../models';
import {projects} from '../models';
import {sessions} from '../models';
import {settings} from '../models';
import {skills} from '../models';
import {usage} from '../models';

export function AddProject(arg1:string):Promise<void>;

export function GetCommands(arg1:string):Promise<Array<commands.Command>>;

export function GetPlans():Promise<Array<plans.Plan>>;

export function GetPreservedPlans():Promise<Array<plans.Plan>>;

export function GetProjects():Promise<Array<projects.Project>>;

export function GetSessionTranscript(arg1:string,arg2:string):Promise<Array<sessions.TranscriptMessage>>;

export function GetSessions():Promise<Array<sessions.Session>>;

export function GetSettings(arg1:string):Promise<Array<settings.SettingsFile>>;

export function GetSkills(arg1:string):Promise<Array<skills.Skill>>;

export function GetUsageStats():Promise<usage.StatsCache>;

export function PickProjectDir():Promise<string>;

export function RemoveProject(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SetPlanMeta(arg1:string,arg2:plans.PlanMeta):Promise<void>;

export function SetPlanName(arg1:string,arg2:string):Promise<void>;

export function SetProjectLastOpened(arg1:string):Promise<void>;

export function UpdateCommand(arg1:string,arg2:string):Promise<void>;

export function UpdateSettings(arg1:string,arg2:string):Promise<void>;
