// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlans() {
  return window['go']['main']['App']['GetPlans']();
}

export function GetSessionTranscript(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTranscript'](arg1, arg2);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}
