// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetClaudeMd(arg1) {
  return window['go']['main']['App']['GetClaudeMd'](arg1);
}

export function GetCommands(arg1) {
  return window['go']['main']['App']['GetCommands'](arg1);
}

export function GetMcpServers() {
  return window['go']['main']['App']['GetMcpServers']();
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetPlans() {
  return window['go']['main']['App']['GetPlans']();
}

export function GetPreservedPlans() {
  return window['go']['main']['App']['GetPreservedPlans']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSessionTranscript(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTranscript'](arg1, arg2);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function GetSkills(arg1) {
  return window['go']['main']['App']['GetSkills'](arg1);
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function PickProjectDir() {
  return window['go']['main']['App']['PickProjectDir']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function ResumeSession(arg1, arg2) {
  return window['go']['main']['App']['ResumeSession'](arg1, arg2);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SetMcpServers(arg1) {
  return window['go']['main']['App']['SetMcpServers'](arg1);
}

export function SetNoteMeta(arg1, arg2) {
  return window['go']['main']['App']['SetNoteMeta'](arg1, arg2);
}

export function SetNoteTitle(arg1, arg2) {
  return window['go']['main']['App']['SetNoteTitle'](arg1, arg2);
}

export function SetPlanMeta(arg1, arg2) {
  return window['go']['main']['App']['SetPlanMeta'](arg1, arg2);
}

export function SetPlanName(arg1, arg2) {
  return window['go']['main']['App']['SetPlanName'](arg1, arg2);
}

export function SetProjectLastOpened(arg1) {
  return window['go']['main']['App']['SetProjectLastOpened'](arg1);
}

export function UpdateClaudeMd(arg1, arg2) {
  return window['go']['main']['App']['UpdateClaudeMd'](arg1, arg2);
}

export function UpdateCommand(arg1, arg2) {
  return window['go']['main']['App']['UpdateCommand'](arg1, arg2);
}

export function UpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2);
}
