// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usage} from '../models';

export function GetUsageStats():Promise<usage.StatsCache>;
