// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function GetPlans() {
  return window['go']['main']['App']['GetPlans']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSessionTranscript(arg1, arg2) {
  return window['go']['main']['App']['GetSessionTranscript'](arg1, arg2);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings(arg1) {
  return window['go']['main']['App']['GetSettings'](arg1);
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function PickProjectDir() {
  return window['go']['main']['App']['PickProjectDir']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SetProjectLastOpened(arg1) {
  return window['go']['main']['App']['SetProjectLastOpened'](arg1);
}

export function UpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2);
}
