// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plans} from '../models';
import {sessions} from '../models';
import {usage} from '../models';

export function GetPlans():Promise<Array<plans.Plan>>;

export function GetSessionTranscript(arg1:string,arg2:string):Promise<Array<sessions.TranscriptMessage>>;

export function GetSessions():Promise<Array<sessions.Session>>;

export function GetUsageStats():Promise<usage.StatsCache>;
